export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as ReadList } from "./Readlist";
export { default as FeedLatest } from "./FeedLatest";
export { default as FeedPop } from "./FeedPop";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Banner } from "./Banner";
export { default as Login } from "./Login";
export { default as StaffPickBorder } from "./StaffPickBorder";
export { default as ReadListBorder } from "./ReadListBorder";
export { default as Latestpopularboarder } from "./Latestpopularboarder";
// export { default as Category } from "./CategoryBorder";
export { default as ShortStory} from "./Category/Shortstory";
export { default as Emotion} from "./Category/Emotion";
export { default as Experience} from "./Category/Experience";
export { default as Inspiration} from "./Category/Inspiration";
export { default as Knowledge} from "./Category/Knowledge";
export { default as Idea} from "./Category/Idea";
export { default as FeedPopWeek} from "./FeedPopWeek";
export { default as Notfound} from "./Notfound";
export { default as Philosophy} from "./Philosophy";
export { default as UserAgreement} from "./UserAgreement";
export { default as CreativeCommons} from "./CreativeCommons";
export { default as InsideReadlist} from "./InsideReadlist";
export { default as ProfileBorder} from "./ProfileBorder";
